language: node_js
node_js:
  - '4.1'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
services:

branches:
  only:
  - master

env:
  - CXX=g++-4.8

before_install:
  - npm update -g npm
  - npm --version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  # - npm install --save-dev ionic
  - npm install -g codeclimate-test-reporter

before_script:

script:
  - npm run-script test-travis

after_success:
  - codeclimate-test-reporter < coverage/coverage.lcov

cache:
  bundler: true
  directories:
  - node_modules # NPM packages

notifications:
  email: true
