language: csharp
solution: HAppi.sln
install:
  - nuget restore HAppi.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release HAppi.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./HAppi.ClassLibrary.UnitTests/bin/Release/HAppi.ClassLibrary.UnitTests.dll